class MotivationalMessages {
  static List<String> messages = [
    "Every new day is a new chance to rebuild your life.",
    "You are stronger than the urges that try to pull you back.",
    "Healing is not a straight line—keep moving forward.",
    "Your future self will thank you for choosing recovery today.",
    "Small steps every day lead to big change.",
    "You deserve a life filled with peace, clarity, and freedom.",
    "You’ve already survived the hardest parts—keep going.",
    "Recovery is difficult, but regret is worse.",
    "Focus on progress, not perfection.",
    "Be proud of how far you’ve come—you’re not the person you used to be.",
    "Stay patient. Your healing is happening slowly but surely.",
    "You are not your past. You are building something new.",
    "One day at a time. One victory at a time.",
    "Cravings fade, but your strength remains.",
    "The best project you’ll ever work on is yourself.",
    "You are capable of more than you think.",
    "Your recovery is proof that change is real.",
    "You don’t have to be perfect; you just have to show up.",
    "Every moment you stay clean, you rewrite your story.",
    "Choose the future you want, not the comfort that harms you.",
    "Your mind is your strongest weapon—train it with purpose.",
    "You are not alone in this journey.",
    "Take a deep breath. You’re doing better than you think.",
    "Freedom begins the moment you choose courage over fear.",
    "Celebrate every win, no matter how small.",
    "Difficult roads lead to beautiful destinations.",
    "You are breaking a cycle—be proud of that strength.",
    "Your comeback will be stronger than your struggle.",
    "Be kind to yourself today; you’re still healing.",
    "Recovery is not about being strong all the time—it’s about never giving up."
  ];
}
