// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwfI8gyDLkz6XfB5-tM4bD6M8P1HBx4ok',
    appId: '1:1036090460961:web:6ce2d61001d0d61e364c60',
    messagingSenderId: '1036090460961',
    projectId: 't3afiii',
    authDomain: 't3afiii.firebaseapp.com',
    storageBucket: 't3afiii.firebasestorage.app',
    measurementId: 'G-05Q7YLE30M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwQf_mUjn3YSkkRWIX3GNbRFcMvIK7dFM',
    appId: '1:1036090460961:android:318cfab8caef4d58364c60',
    messagingSenderId: '1036090460961',
    projectId: 't3afiii',
    storageBucket: 't3afiii.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxDgVq-5mwpDB_1iwG9zK2Gu_MJ-1DFmQ',
    appId: '1:1036090460961:ios:67c1e0910541eb83364c60',
    messagingSenderId: '1036090460961',
    projectId: 't3afiii',
    storageBucket: 't3afiii.firebasestorage.app',
    iosBundleId: 'com.example.t3afy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxDgVq-5mwpDB_1iwG9zK2Gu_MJ-1DFmQ',
    appId: '1:1036090460961:ios:67c1e0910541eb83364c60',
    messagingSenderId: '1036090460961',
    projectId: 't3afiii',
    storageBucket: 't3afiii.firebasestorage.app',
    iosBundleId: 'com.example.t3afy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwfI8gyDLkz6XfB5-tM4bD6M8P1HBx4ok',
    appId: '1:1036090460961:web:df9dcb9b46233fbe364c60',
    messagingSenderId: '1036090460961',
    projectId: 't3afiii',
    authDomain: 't3afiii.firebaseapp.com',
    storageBucket: 't3afiii.firebasestorage.app',
    measurementId: 'G-NQD9CY1VNN',
  );
}
